name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js for frontend
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Build frontend
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
              run: |
                  cd frontend
                  npm run build

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub

            - name: Debug USER_IP
              run: echo "${{ secrets.USER_IP }}"

            - name: List .ssh directory
              run: ls -la ~/.ssh/

            - name: Print known_hosts
              run: cat ~/.ssh/known_hosts

            - name: Deploy frontend to Apache
              env:
                  USER_IP: ${{ secrets.USER_IP }}
              run: |
                  scp -o StrictHostKeyChecking=no -r frontend/build/* $USER_IP:/var/www/html/
                  ssh -o StrictHostKeyChecking=no $USER_IP << 'EOF'
                    sudo systemctl restart apache2
                  EOF
