name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js for frontend
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Build frontend
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
                  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
              run: |
                  cd frontend
                  npm run build

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $(echo "${{ secrets.USER_IP }}" | cut -d'@' -f2) >> ~/.ssh/known_hosts

            - name: Deploy frontend and backend
              env:
                  USER_IP: ${{ secrets.USER_IP }}
              run: |
                  echo "Starting deployment"
                  scp -o StrictHostKeyChecking=no -r frontend/build/* $USER_IP:/var/www/html/
                  if [ $? -ne 0 ]; then
                    echo "Error during scp"
                    exit 1
                  fi
                  echo "Files copied to server"
                  ssh -tt -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 $USER_IP << 'EOF'
                    set -x
                    echo "Restarting nginx"
                    sudo systemctl restart nginx
                    if [ $? -ne 0 ]; then
                      echo "Error restarting nginx"
                      exit 1
                    fi
                    echo "Nginx restarted successfully"

                    echo "Navigating to backend directory"
                    cd /var/www/MacroDash/backend
                    if [ $? -ne 0 ]; then
                      echo "Error navigating to backend directory"
                      exit 1
                    fi

                    echo "Pulling latest code from git"
                    git pull origin master
                    if [ $? -ne 0 ]; then
                      echo "Error pulling latest code from git"
                      exit 1
                    fi

                    echo "Activating virtual environment"
                    source venv/bin/activate
                    if [ $? -ne 0 ]; then
                      echo "Error activating virtual environment"
                      exit 1
                    fi

                    echo "Installing dependencies"
                    pip install -r requirements.txt
                    if [ $? -ne 0 ]; then
                      echo "Error installing dependencies"
                      exit 1
                    fi

                    echo "Reloading systemd daemon"
                    sudo systemctl daemon-reload
                    if [ $? -ne 0 ]; then
                      echo "Error reloading systemd daemon"
                      exit 1
                    fi

                    echo "Restarting gunicorn"
                    sudo systemctl restart gunicorn
                    if [ $? -ne 0 ]; then
                      echo "Error restarting gunicorn"
                      exit 1
                    fi
                    echo "Gunicorn restarted successfully"
                  EOF
