name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js for frontend
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Build frontend
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
                  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
              run: |
                  cd frontend
                  npm run build

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $(echo "${{ secrets.USER_IP }}" | cut -d'@' -f2) >> ~/.ssh/known_hosts

            - name: Deploy frontend to Nginx
              env:
                  USER_IP: ${{ secrets.USER_IP }}
              run: |
                  scp -o StrictHostKeyChecking=no -r frontend/build/* $USER_IP:/var/www/html/
                  ssh -tt -o StrictHostKeyChecking=no $USER_IP << 'EOF'
                    sudo systemctl restart nginx
                  EOF

            - name: Deploy backend to Gunicorn
              env:
                  USER_IP: ${{ secrets.USER_IP }}
              run: |
                  ssh -tt -o StrictHostKeyChecking=no $USER_IP << 'EOF'
                    cd /var/www/MacroDash/backend
                    git pull origin master
                    source venv/bin/activate
                    pip install -r requirements.txt
                    sudo systemctl daemon-reload
                    sudo systemctl restart gunicorn
                  EOF
