name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js for frontend
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Build frontend
              env:
                  NODE_OPTIONS: --max_old_space_size=4096
              run: |
                  cd frontend
                  npm run build

            - name: Add SSH key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy frontend to Apache
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  USER: ${{ secrets.USER }}
              run: |
                  scp -o StrictHostKeyChecking=no -r frontend/build/* $USER@$SERVER_IP:/var/www/html/
                  ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP << 'EOF'
                    sudo systemctl restart apache2
                  EOF
